version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - go-network
    depends_on:
      - redis
    environment:
      - LISTEN_PORT=8080
      - REDIS_HOST=redis:6379

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - go-network

networks:
  go-network:
    driver: bridge